import { Muxer, ArrayBufferTarget } from 'mp4-muxer';

function elasticEaseOut(t: number): number {
  const c4 = (2 * Math.PI) / 3;
  return t === 0 ? 0 : t === 1 ? 1 : Math.pow(2, -10 * t) * Math.sin((t * 10 - 0.75) * c4) + 1;
}

function easeOutQuart(t: number): number {
  return 1 - Math.pow(1 - t, 4);
}

self.onmessage = async (e) => {
  const { type, payload } = e.data;
  if (type === 'RENDER_CHUNK') {
    const { chunkIndex, startFrame, endFrame, fps, width, height, text, scenes } = payload;
    
    try {
      if (typeof OffscreenCanvas === 'undefined') {
        throw new Error('OffscreenCanvas non supporté par ce navigateur.');
      }
      if (typeof VideoEncoder === 'undefined') {
        throw new Error('VideoEncoder non supporté par ce navigateur.');
      }

      // 1. Setup OffscreenCanvas
      const canvas = new OffscreenCanvas(width, height);
      const ctx = canvas.getContext('2d', { alpha: false });
      if (!ctx) throw new Error('Failed to get 2d context');

      // 2. Setup Muxer & Encoder
      const muxer = new Muxer({
        target: new ArrayBufferTarget(),
        video: { codec: 'avc', width, height },
        fastStart: 'in-memory',
      });

      let encoderError: Error | null = null;
      const videoEncoder = new VideoEncoder({
        output: (chunk, meta) => muxer.addVideoChunk(chunk, meta),
        error: (err) => {
          console.error('VideoEncoder error:', err);
          encoderError = err;
        },
      });

      const config: VideoEncoderConfig = {
        codec: 'avc1.42E028', // Baseline profile, level 4.0
        width,
        height,
        bitrate: 5_000_000,
        framerate: fps,
        hardwareAcceleration: 'prefer-hardware',
      };

      const support = await VideoEncoder.isConfigSupported(config);
      if (!support.supported) {
        config.hardwareAcceleration = 'no-preference';
        const support2 = await VideoEncoder.isConfigSupported(config);
        if (!support2.supported) {
           throw new Error('Configuration VideoEncoder non supportée.');
        }
      }

      videoEncoder.configure(config);

      // 3. Render Loop (GPU Accelerated via Canvas API)
      const totalFrames = endFrame - startFrame;
      
      const sceneStarts: number[] = [];
      let currentStart = 0;
      const validScenes = scenes && scenes.length > 0 ? scenes : [{
        title: text || 'تصدير الفيديو...',
        subtitle: 'Generated by AI',
        color: '#38bdf8',
        bgColor: '#0f172a',
        durationInFrames: totalFrames
      }];

      for (const s of validScenes) {
        sceneStarts.push(currentStart);
        currentStart += s.durationInFrames;
      }

      for (let i = 0; i < totalFrames; i++) {
        if (encoderError) throw encoderError;

        // Find current scene
        let sceneIdx = 0;
        for (let s = 0; s < validScenes.length; s++) {
          if (i >= sceneStarts[s]) sceneIdx = s;
        }
        const scene = validScenes[sceneIdx];
        const sceneFrame = i - sceneStarts[sceneIdx];
        const sceneDuration = scene.durationInFrames;

        // Clear background
        ctx.fillStyle = scene.bgColor || '#0f172a';
        ctx.fillRect(0, 0, width, height);

        // Dynamic Background (Moving Gradient)
        const moveX = Math.sin(i / 60) * 300;
        const moveY = Math.cos(i / 60) * 300;
        
        const gradient = ctx.createRadialGradient(
          width / 2 + moveX, height / 2 + moveY, 0,
          width / 2 + moveX, height / 2 + moveY, width * 1.2
        );
        gradient.addColorStop(0, `${scene.color || '#38bdf8'}60`);
        gradient.addColorStop(1, 'transparent');
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, width, height);

        // Grid overlay
        ctx.strokeStyle = 'rgba(255,255,255,0.04)';
        ctx.lineWidth = 2;
        const gridSize = 80;
        const offsetX = (i * 2) % gridSize;
        const offsetY = (i * 2) % gridSize;
        ctx.beginPath();
        for (let x = -gridSize; x < width + gridSize; x += gridSize) {
          ctx.moveTo(x + offsetX, 0);
          ctx.lineTo(x + offsetX, height);
        }
        for (let y = -gridSize; y < height + gridSize; y += gridSize) {
          ctx.moveTo(0, y + offsetY);
          ctx.lineTo(width, y + offsetY);
        }
        ctx.stroke();

        // Camera Zoom effect
        const zoom = 1 + (sceneFrame / sceneDuration) * 0.15;
        ctx.save();
        ctx.translate(width / 2, height / 2);
        ctx.scale(zoom, zoom);
        ctx.translate(-width / 2, -height / 2);

        // Title Animation (Kinetic Typography)
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        
        // Handle RTL for Arabic
        const isArabic = /[\u0600-\u06FF]/.test(scene.title);
        ctx.direction = isArabic ? 'rtl' : 'ltr';
        
        const title = scene.title.toUpperCase();
        const words = title.split(' ');
        
        ctx.font = '900 110px sans-serif';
        const lineHeight = 130;
        const totalTextHeight = words.length * lineHeight;
        const startY = height / 2 - totalTextHeight / 2;

        for (let w = 0; w < words.length; w++) {
          const word = words[w];
          const delay = w * 4;
          let t = Math.max(0, sceneFrame - delay) / 15;
          if (t > 1) t = 1;
          
          const scale = t === 0 ? 0 : elasticEaseOut(t);
          const opacity = t === 0 ? 0 : Math.min(1, t * 2);
          
          ctx.save();
          ctx.translate(width / 2, startY + w * lineHeight);
          ctx.scale(scale, scale);
          
          // Shadow
          ctx.shadowColor = 'rgba(0,0,0,0.8)';
          ctx.shadowBlur = 30;
          ctx.shadowOffsetY = 15;
          
          ctx.fillStyle = `rgba(255, 255, 255, ${opacity})`;
          ctx.fillText(word, 0, 0);
          
          // Highlight alternate words
          if (w % 2 !== 0) {
             ctx.fillStyle = scene.color || '#38bdf8';
             ctx.fillText(word, 0, 0);
          }
          
          ctx.restore();
        }

        // Subtitle Animation
        let subT = Math.max(0, sceneFrame - 25) / 20;
        if (subT > 1) subT = 1;
        const subOpacity = easeOutQuart(subT);
        const subY = startY + words.length * lineHeight + 60 + (1 - easeOutQuart(subT)) * 50;
        
        ctx.font = '600 45px sans-serif';
        ctx.fillStyle = `rgba(255, 255, 255, ${subOpacity * 0.9})`;
        
        // Subtitle shadow
        ctx.shadowColor = 'rgba(0,0,0,0.6)';
        ctx.shadowBlur = 15;
        ctx.shadowOffsetY = 5;
        
        // Split subtitle into lines if it's too long
        const subWords = scene.subtitle.split(' ');
        let currentLine = '';
        let lineIndex = 0;
        
        for (let n = 0; n < subWords.length; n++) {
          const testLine = currentLine + subWords[n] + ' ';
          const metrics = ctx.measureText(testLine);
          if (metrics.width > width * 0.8 && n > 0) {
            ctx.fillText(currentLine, width / 2, subY + lineIndex * 60);
            currentLine = subWords[n] + ' ';
            lineIndex++;
          } else {
            currentLine = testLine;
          }
        }
        ctx.fillText(currentLine, width / 2, subY + lineIndex * 60);

        ctx.restore(); // Restore camera zoom

        // Scene Transition (Flash/Wipe)
        if (sceneFrame < 12 && sceneIdx > 0) {
          const flashOpacity = 1 - (sceneFrame / 12);
          ctx.fillStyle = `rgba(255, 255, 255, ${flashOpacity})`;
          ctx.fillRect(0, 0, width, height);
        }

        // Progress bar indicator
        const globalProgress = i / totalFrames;
        ctx.fillStyle = scene.color || '#10b981';
        ctx.fillRect(0, height - 12, globalProgress * width, 12);

        const timestamp = (i * 1e6) / fps;
        const frameObj = new VideoFrame(canvas, { timestamp });
        const keyFrame = i % fps === 0;
        
        videoEncoder.encode(frameObj, { keyFrame });
        frameObj.close(); // Strict memory cleanup

        if (i % 10 === 0) {
          (self as unknown as Worker).postMessage({ type: 'PROGRESS', payload: { chunkIndex, progress: i / totalFrames } });
        }
      }

      await videoEncoder.flush();
      if (encoderError) throw encoderError;
      
      muxer.finalize();

      const buffer = muxer.target.buffer;
      (self as unknown as Worker).postMessage({ type: 'CHUNK_COMPLETE', payload: { chunkIndex, buffer } }, [buffer]);
    } catch (error: any) {
      (self as unknown as Worker).postMessage({ type: 'ERROR', payload: { chunkIndex, error: error.message || String(error) } });
    }
  }
};
